// Generated by CoffeeScript 1.12.7
(function() {
  var gg, kk;

  gg = function(x) {
    return kk(x);
  };

  kk = function(x) {
    return console.log(x + 1);
  };

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLS1vdXRwdXQuanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyItLW91dHB1dCJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBRUk7QUFBQSxNQUFBOztFQUFBLEVBQUEsR0FBSSxTQUFDLENBQUQ7V0FBTyxFQUFBLENBQUcsQ0FBSDtFQUFQOztFQUlKLEVBQUEsR0FBSSxTQUFDLENBQUQ7V0FBTyxPQUFPLENBQUMsR0FBUixDQUFZLENBQUEsR0FBRyxDQUFmO0VBQVA7QUFKSiIsInNvdXJjZXNDb250ZW50IjpbIiMgYXNkYXNcblxuICAgIGdnPSAoeCkgLT4ga2soeCkgXG5cbiMgYXNkYXNcblxuICAgIGtrPSAoeCkgLT4gY29uc29sZS5sb2cgeCsgMVxuIl19
//# sourceURL=/Users/timm/gits/koffee/script/tmp/--output