// Generated by CoffeeScript 1.12.7
(function() {
  var gg, kk;

  ({
    fff: function(x) {
      if (x == null) {
        x = 1;
      }
      return gg(x);
    }
  });

  gg = function(x) {
    return kk(x);
  };

  kk = function(x) {
    return console.log(x + 1);
  };

}).call(this);
