#!/usr/bin/env bash

cat <<-EOF > "/tmp/$$.head"
[home](http://tiny.cc/koffeed) |
[copyright](https://github.com/koffeed/src/blob/master/LICENSE.md) &copy;2017, tim&commat;menzies.us<br>
[<img width=900 src=https://raw.githubusercontent.com/koffeed/src/master/img/header.png>](http://tiny.cc/koffeed)<br>
[src](https://github.com/koffeed/src/tree/master/lib) |
[tour](https://github.com/koffeed/src/blob/master/docs/TOUR.md) |
[style](https://github.com/koffeed/src/blob/master/docs/STYLE.md) 
______

EOF



gawk '
BEGIN { RS = "" ; FS = "\n" }
NR==1 {system("cat " f) ; next }
1     {print $0 "\n" }
' f="/tmp/$$.head" $1 > "/tmp/$$.out"

mv "/tmp/$$.out"  $1
