#!/usr/bin/env bash

header() {
cat <<-EOF
[home](http://tiny.cc/koff) |
[copyright](https://github.com/koffee/script/blob/master/LICENSE.md) &copy;2017, tim&commat;menzies.us<br>
[<img width=900 src=https://raw.githubusercontent.com/koffee/script/master/img/header.png>](http://tiny.cc/koffeed)<br>
[src](https://github.com/koffee/script/tree/master/lib) |
[tour](https://github.com/koffee/script/blob/master/docs/TOUR.md) |
[style](https://github.com/koffee/script/blob/master/docs/STYLE.md) 
______

EOF
}

header
gawk '
      { body = body || $0 ~ /^[ \t]*$/}
body  { print }
     '  $1 #> "/tmp/$$.out"

#mv "/tmp/$$.out"  $1
