#!/usr/bin/env bash

header() {
cat <<'EOF'
[home](http://tiny.cc/koff) |
[copyright](https://github.com/koffee/script/blob/master/LICENSE.md) &copy;2017, tim&commat;menzies.us<br>
[<img width=900 src=https://raw.githubusercontent.com/koffee/script/master/img/head.jpg>](http://tiny.cc/koffee)<br>
[src](https://github.com/koffee/script/tree/master/lib) |
[tour](https://github.com/koffee/script/blob/master/docs/TOUR.md) |
[style](https://github.com/koffee/script/blob/master/docs/STYLE.md) 
EOF
}

f="/tmp/$$.out"

(header 
cat $1 | gawk '
/^[ \t]*$/  { body = 1 }
body        { print $0 }
'
)  > $f

mv $f $1
