
task 'setup', "Set stuff up (needs only to be sh once)", ->
  make ".gitignore", gitignore

task 'update', 'Update from github', ->
	sh "git pull"

option '-w', '--who [GH Peson]', "set github user.name for 'github'"
option '-e', '--elm [GH email]', "set github user.email for 'github'"

task 'github', 'Setup for github', (the)->
   who = the.who or "'Tim Menzies'"
   elm = the.elm or "'tim.menzies@gmail.com'"
   sh 'git config --global user.name '  + who
   sh 'git config --global user.email ' + elm

task 'commit', 'Push back to  github', ->
  sh "git status"
  sh "git commit -am 'committing'"
  sh "git push"

task 'inspire', "So you think you're so great?", ->
  console.log alexy

alexy="""
        'The stars and the sun are everywhere… I did not expect all this.
        The silence struck me. I could hear my heart beating so clearly.
        I could hear my breath – it even hurt to think.'
        -- Alexy Leonev

        On March 18, 1965, Alexey Leonov stepped outside the thin
        metal shell of Voskhod-2 to float in the harsh void of
        space. For 12 minutes and 9 seconds, Leonov opened the doors
        on an entire new branch of exploration as the first
        spacewalker. It was nearly a disaster.

        Leonov’s spacesuit had bloated and stiffened in the vacuum,
        and was too large and inflexible to reenter the airlock.  He
        opened a valve to slowly release oxygen, depressurizing his
        suit until it was small enough to squeeze within the
        relative safety of the spacecraft.

        His bad luck continued with a harrowing end to the Voskhod-2
        mission. The craft malfunctioned during reentry and the
        automatic re-entry system failed to fire, sending them
        wildly off-course. Worse still, the orbital module failed to
        separate, sending them tumbling. When they finally reached
        solid ground, Leonov and fellow creman Belyayev were greeted
        by wolves and bears when the spacecraft dropped them in the
        middle of a thick forest during a snowstorm.

        It was mating season, so the wolves and bears were even more
        aggressive than usual. The forest was too thick for a rescue
        helicopter to land. They’d opened the hatch with explosive
        bolts on landing, leaving the cosmonauts exposed to the
        storm and subzero temperatures. The electrical system
        malfunctioned, knocking out the heater while the fans ran at
        full blast. Sweat in their spacesuits threatened to freeze,
        forcing them to wring the suits out to prevent frostbite. A
        rescue party on skis finally reached them the second day,
        chopping wood for a small log cabin and an enormous bonfire.
        Most importantly, the rescuers brought brandy to celebrate
        the triumphant mission. The next morning, the cosmonauts
        skied several kilometres to a pickup location.

        Postscript: At the time of this writing (August 2017), he is
        still alive and kicking. Clearly, nothing can kill this guy.
      """

gitignore="""
        #vimstuff
        [._]*.s[a-w][a-z]
        [._]s[a-w][a-z]
        *.un~
        Session.vim
        netrwhist
        *~
        # sed stuff
        *.bak
        # doc stuff
        docs
        locco
        # mac stuff
        .DS_Store
        # testing stuff
        _allok.lua
        * coffeescript stuff
        raw
        presentation
        test.coffee
        test*.coffee
        test.coffee.md
        test*.coffee.md
        test/*.js
        parser.output
        /node_modules
        npm-debug.log*

        """
#############################################

sh = (com, callback=((-> true))) ->
  {exec} = require 'child_process'
  console.log com
  coffee = exec com
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
  coffee.stdout.on 'data', (data) ->
    console.log ">",data.toString()
  coffee.on 'exit', (code) ->
    callback?() if code is 0

make = (file,str) ->
  fs     = require 'fs'
  fs.exists file, (( exists ) ->
    if not exists
      fs.writeFile file , str, (error) ->
        console.error("Error writing file", error) if error),
    sh "git add " + file


